Authentication System Added
csivitu/Riddler-Backend-2022 pull request #4
Opened 2022-07-31 06:15 UTC by Pratham-Mishra04

Joi Validator added with all the changes specified by the Sr. Core

2022-07-31 15:52 UTC, sanjaybaskaran01 requested changes
Create envHandler so that it throws error if necessary env is not present, Make changes to current reviews so that it is executable without errors

2022-07-31 15:52 UTC, sanjaybaskaran01 commented on README.md
> +# Riddler-Backend-2022
Removes existing README.MD Template

2022-07-31 15:52 UTC, sanjaybaskaran01 commented on app.js
> +import { noURL } from "./Controllers/ErrorController.js";
Causes error since controller folder is not capital but here it is capital
![image](https://user-images.githubusercontent.com/72266283/182034334-83533890-e683-4bc2-b060-4507e9345839.png)

2022-07-31 15:52 UTC, sanjaybaskaran01 commented on package.json
> +  }
libphonenumber-js package is not here, so it will raise error

2022-07-31 15:52 UTC, sanjaybaskaran01 commented on routers/userRouter.js
> +import { signup, login, protect, logout } from "../Controllers/authController.js";
Import URL is incorrect because of capitalization

2022-07-31 15:52 UTC, sanjaybaskaran01 commented on routers/userRouter.js
> +import { getAllUsers, UpdatePassword, getUser, updateUser, deleteUser, filterBody, forgotPassword, resetPassword, uploadProficPic, resizePic } from "../Controllers/userController.js";
Import URL is incorrect because of capitalization

2022-07-31 15:52 UTC, sanjaybaskaran01 commented on utils/joiValidator.js
> +        const user= await User.find({email: value});
Interesting implementation :boom:

2022-08-01 03:50 UTC, Pratham-Mishra04 commented on utils/joiValidator.js
> +        const user= await User.find({email: value});
Thank You😁

2022-08-02 06:18 UTC, sanjaybaskaran01 approved these changes

2022-08-02 06:20 UTC, sanjaybaskaran01 approved these changes

2022-08-02 06:24 UTC, merged